apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: medical-chatbot-monitor
  namespace: medical-chatbot
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: medical-chatbot
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
